services:
  - type: web
    name: n8n
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: DB_TYPE
        value: postgres
      - key: DB_POSTGRESDB_HOST
        fromDatabase:
          name: n8n-db
          property: host
      - key: DB_POSTGRESDB_PORT
        fromDatabase:
          name: n8n-db
          property: port
      - key: DB_POSTGRESDB_DATABASE
        fromDatabase:
          name: n8n-db
          property: database
      - key: DB_POSTGRESDB_USER
        fromDatabase:
          name: n8n-db
          property: user
      - key: DB_POSTGRESDB_PASSWORD
        fromDatabase:
          name: n8n-db
          property: password
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        sync: false  # Set in Render dashboard for security
      - key: N8N_BASIC_AUTH_PASSWORD
        sync: false  # Set in Render dashboard for security
      - key: WEBHOOK_URL
        value: https://your-subdomain.onrender.com/  # Replace with your actual Render URL
      - key: N8N_RUNNERS_ENABLED
        value: "true"
      - key: N8N_RUNNERS_MODE
        value: "internal"
      - key: N8N_RUNNERS_MAX_CONCURRENCY
        value: "5"
      - key: N8N_RUNNERS_TASK_TIMEOUT
        value: "60"
      - key: N8N_RUNNERS_HEARTBEAT_INTERVAL
        value: "30"
      - key: N8N_RUNNERS_BROKER_LISTEN_ADDRESS
        value: "0.0.0.0"

databases:
  - name: n8n-db
    plan: free
