services:
  - type: web
    name: n8n
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_HOST
        fromDatabase:
          name: n8n-db
          property: host
      - key: DB_POSTGRESDB_PORT
        fromDatabase:
          name: n8n-db
          property: port
      - key: DB_POSTGRESDB_DATABASE
        fromDatabase:
          name: n8n-db
          property: database
      - key: DB_POSTGRESDB_USER
        fromDatabase:
          name: n8n-db
          property: user
      - key: DB_POSTGRESDB_PASSWORD
        fromDatabase:
          name: n8n-db
          property: password
      - key: DB_POSTGRESDB_SSL
        value: "true"

      - key: PORT
        value: "5678"
      - key: N8N_PORT
        value: "5678"

      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        sync: false
      - key: N8N_BASIC_AUTH_PASSWORD
        sync: false

      - key: WEBHOOK_URL
        value: https://n8n-rjhi.onrender.com

      - key: N8N_ENCRYPTION_KEY
        sync: false

      - key: N8N_LOG_LEVEL
        value: debug

      - key: N8N_RUNNERS_ENABLED
        value: "true"
      - key: N8N_RUNNERS_MODE
        value: "internal"
      - key: N8N_RUNNERS_MAX_CONCURRENCY
        value: "5"
      - key: N8N_RUNNERS_TASK_TIMEOUT
        value: "60"
      - key: N8N_RUNNERS_HEARTBEAT_INTERVAL
        value: "30"
      - key: N8N_RUNNERS_BROKER_LISTEN_ADDRESS
        value: "0.0.0.0"

databases:
  - name: n8n-db
    plan: free
